### ISSUE TITLE
Raspberry Pi 2 support

### ISSUE THREAD

**Issue by robinvalk** [KABA-CCEAC/node-ftdi#15]
Hi,

Is Raspberry Pi 2 support planned or has anyone made it work?
The install script doesn't support the pi2. But even after installing the right driver manually the `node-gyp rebuild` failed.
(The Pi 2 has an armv7l architecture)

I cant get it in working order...

**Comment by chintanp** [comment]
@robinvalk Were you able to solve it or think of any work-around ?

**Comment by robinvalk** [comment]
Nope, bailed the hole thing eventually.

**Comment by chintanp** [comment]
@robinvalk : I was told on the chat support on node-serialport that once the ftdi device drivers are in place, the ftdi device is treated just like any other serial device and existing libraries and other concepts  remain the same. What are your thoughts about this ? Node-seralport didnt work for me, so I was wondering whether this is device specific or a general phenomenon.

**Comment by robinvalk** [comment]
I have no clue, that's way over my head.

I think I close the issue, if someone has figured it out I hope they'll document it.
